let computer = {
  name: "Asus",
  hardware: {
    manufacter: "Asus",
    screen_size: "9in",
    motherboard: "Asus",
    cpu: "intel i7",
    ram: "8G"
  },
  keys: [{
    name: "a",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "b",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "c",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "d",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "e",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "f",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "f",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "g",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "h",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "i",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "j",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "k",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "l",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "m",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "n",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "o",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "p",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "q",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "r",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "s",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "t",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "u",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "v",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "w",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "x",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "y",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "z",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: ",",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: ".",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "/",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: ";",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "'",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "[",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "]",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "=",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "-",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "0",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "9",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "8",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "7",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "6",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "5",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "4",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "3",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "2",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "1",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "`",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "f1",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "f2",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "f3",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "f4",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "f5",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "f6",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "f7",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "f8",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "f9",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "f10",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "f11",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "f12",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "enter",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "shift",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "caps lock",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "ctrl",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "alt",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "esc",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "delete",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "home",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "pgup",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "pgdn",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "end",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "prt sc",
    ispressed: false,
    isCaps: false,
    isShift: false
  }, {
    name: "pause",
    ispressed: false,
    isCaps: false,
    isShift: false
  },]
}
let parents = [{
  name: "Becky",
  relationship: "Mother",
}, {
  name: "Steven",
  relationship: "Father"
}]
let cory = {
  name: "Cory",
  wife: "Susan",
  parents: parents,
  lastName: "Brighton",
  kids: [
    {
      name: "Jarom",
      age: 15
    },
    {
      name: "Josiah",
      age: 11
    },
    {
      name: "Kimball",
      age: 10
    }
  ],
  favColor: "blue",
  pets: {
    dog: [
      {
        name: "Cinder",
        breed: "poodle",
        tricks: ["fetch", "high 5", "sit", "down", "roll over"]
      },
      {
        name: "Ellie",
        breed: "French Bulldog",
        tricks: ["high 5", "sit", "roll over"]
      }
    ]
  },
  computer: computer
};

let story = `I am ${cory.name} ${cory.lastName}. I have a wife, ${cory.wife} ${cory.lastName}, and ${cory.kids.length} kids, 
${cory.kids["0"].name}, ${cory.kids["1"].name}, and ${cory.kids["2"].name}. They are ${cory.kids["0"].age}, ${cory.kids["1"].age},
 and ${cory.kids["2"].age}. We have ${cory.pets.dog.length} dogs. They are ${cory.pets.dog["0"].name} 
 our ${cory.pets.dog["0"].breed} and ${cory.pets.dog["1"].name} our ${cory.pets.dog["1"].breed}. 
 We named them and then realized we have ${cory.pets.dog["0"].name} ${cory.pets.dog["1"].name}.`;

console.log(story);